config/routes.rb
Cfa::Application.routes.draw do
  
  

  root :to => "home#index"
  
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources :users
  resources :campaigns do
    collection do
      get 'get_campaigns_data'
      get 'search_pending_campaign'
      get 'get_calls_stat'
    end
    member do
      get 'get_calls_forever'
      get 'get_calls_today'
      get 'get_donation_amount'
      get 'get_calls_in_progress'
      get 'get_population_destribution_pyramid_chart', :format => :xml
    end
  end

  resources :campaign_globals do
    collection do
      get 'get_total_calls_forever'
      get 'get_total_calls_today'
      get 'get_donation_remaining'
      get 'get_calls_in_progress'
    end
  end

  resources :donations do
    collection do
      get 'has_donated'
    end
  end

  match 'donations/express_checkout' => "donations#express_checkout", :as => :donations_express_checkout, :via => :post
  
  ActiveAdmin.routes(self)

end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  
  belongs_to :user
  belongs_to :category
  belongs_to :viciserver
  belongs_to :campaign_type
  
  has_one :campaign_stat, :dependent => :destroy
  has_one :campaign_attribute, :dependent => :destroy
  
  has_many :campaign_stats_custom, :dependent => :destroy
  has_many :campaign_stats_geo, :dependent => :destroy
  has_many :donations, :dependent => :destroy
  has_many :campaign_menus, :dependent => :destroy
  has_many :campaign_surveys, :dependent => :destroy
    
  has_many :campaign_images, :dependent => :destroy
  
  attr_accessible :active, :add_to_list_allow, :add_to_list_id, :add_to_list_position, :amount_donated_total, 
                  :amount_donations_today, :campaign_end_date_time, :campaign_start_date_time, :campaign_type_id, 
                  :category_id, :cost_per_call_minute, :description, :inflate_stats_percent, 
                  :internal_notes, :name, :number_donations_today, :number_donations_total, :public_stats_visible, 
                  :shortdescription, :transcript_text, :transcript_audio_file, :user_id, :vici_campaign_id, :viciserver_id,
                  :campaign_images_attributes
                  
  accepts_nested_attributes_for :campaign_images, :allow_destroy => true

  STATUS_ACTIVE = 2
  STATUS_PENDING = 1
  scope :active, where(status: STATUS_ACTIVE)
  scope :pending, where(status: STATUS_PENDING)

  def stats_custom_by_code(status_code, meth)
    rtn_val = campaign_stats_custom.where(status_code: status_code).first.send(meth.to_sym) rescue 0
    return rtn_val || 0
  end

  def get_interested_calls(stat_type)
    interested_calls = 0
    interested_calls = if stats_custom_by_code("SVYEXT",stat_type) > 0
        stats_custom_by_code("SVYEXT",stat_type)
      elsif stats_custom_by_code("SVYREC",stat_type) > 0
        stats_custom_by_code("SVYREC",stat_type)
      elsif stats_custom_by_code("SVYCLM",stat_type) > 0
        stats_custom_by_code("SVYCLM",stat_type)
      end
    return interested_calls
  end

  def self.get_campaigns_hash
    campaigns = Campaign.includes(:campaign_stat).active.limit 10
    campaign_list = campaigns.map{|campaign|
      { campaign_id: campaign.id,
        calls_forever: campaign.campaign_stat.try(:total_calls_made_count_life) || 0,
        calls_today: campaign.campaign_stat.try(:total_calls_made_count_today) || 0,
        calls_in_progress: campaign.campaign_stat.try(:calculated_calls_in_progress) || 0,
        total_donations: campaign.campaign_stat.try(:amount_donations_life) || 0,
        calls_remaining: campaign.campaign_stat.try(:dialable_leads) || 0,
        calls_answered: campaign.stats_custom_by_code("PU","calls_today") || 0,
        calls_interested: campaign.get_interested_calls("calls_today") || 0,
        calls_transferred: campaign.campaign_stat.try(:transferred_count_today) || 0,
        calls_recorded: campaign.campaign_stat.try(:recordings_count_today) || 0,
        left_message: campaign.stats_custom_by_code("AL","calls_today") + campaign.stats_custom_by_code("AA","calls_today"),
        no_answer: campaign.campaign_stat.try(:no_answer_calls_count_today) || 0,
      }
    }
    return campaign_list
  end

  def self.search_pending_campaign(keyword)
    self.includes(:campaign_stat).pending.where("name LIKE ?", "%#{keyword}%").limit 10
  end

  def self.get_calls_stat_hash(campaign_id, status)
    calls_stat_list = []
    campaign = Campaign.includes(:campaign_stat).where(id: campaign_id.to_i).first
    calls_stat_list << if status == "today"
      { campaign_id: campaign.id,
        calls_remaining: campaign.campaign_stat.try(:dialable_leads) || 0,
        calls_answered: campaign.stats_custom_by_code("PU","calls_today") || 0,
        calls_interested: campaign.get_interested_calls("calls_today") || 0,
        calls_transferred: campaign.campaign_stat.try(:transferred_count_today) || 0,
        calls_recorded: campaign.campaign_stat.try(:recordings_count_today) || 0,
        left_message: campaign.stats_custom_by_code("AL","calls_today") + campaign.stats_custom_by_code("AA","calls_today"),
        no_answer: campaign.campaign_stat.try(:no_answer_calls_count_today) || 0,
      }
    elsif status == "forever"
      { campaign_id: campaign.id,
        calls_remaining: campaign.campaign_stat.try(:dialable_leads) || 0,
        calls_answered: campaign.stats_custom_by_code("PU","calls_life") || 0,
        calls_interested: campaign.get_interested_calls("calls_life") || 0,
        calls_transferred: campaign.campaign_stat.try(:transferred_count_life) || 0,
        calls_recorded: campaign.campaign_stat.try(:recordings_count_life) || 0,
        left_message: campaign.stats_custom_by_code("AL","calls_life") + campaign.stats_custom_by_code("AA","calls_life"),
        no_answer: campaign.campaign_stat.try(:no_answer_calls_count_life) || 0,
      }
    end
    return calls_stat_list
  end
end

app/models/campaign_type.rb
class CampaignType < ActiveRecord::Base
  attr_accessible :description, :name, :short_description
  has_many :campaigns
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_filter :authenticate_user!, only: [:new ]
  
  def index
    redirect_to :root
  end

  def show
    @campaign = Campaign.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @campaign }
      format.js
    end
  end
  
  def new
    @campaign = Campaign.new
    @campaign.campaign_images.build
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @campaign }
    end
  end

  # GET /vendors/1/edit
  def edit
    @campaign = Campaign.find(params[:id])
  end

  # POST /vendors
  # POST /vendors.json
  def create
    @campaign = Campaign.new(params[:campaign])
    @campaign.build_campaign_stat
    @campaign.campaign_stats_custom.build
    respond_to do |format|
      if @campaign.save
        
        format.html { redirect_to @campaign, notice: 'Campaign was successfully created and sent for review.' }
        format.json { render json: @campaign, status: :created, location: @campaign }
      else
        format.html { render action: "new" }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /vendors/1
  # PUT /vendors/1.json
  def update
    @campaign = Campaign.find(params[:id])

    respond_to do |format|
      if @campaign.update_attributes(params[:campaign])
        format.html { redirect_to @campaign, notice: 'Campaign was successfully updated and sent for review.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendors/1
  # DELETE /vendors/1.json
  def destroy
    @campaign = Campaign.find(params[:id])
    @campaign.destroy

    respond_to do |format|
      format.html { redirect_to campaigns_url }
      format.json { head :no_content }
    end
  end

  def get_campaigns_data
    comment_list = Campaign.get_campaigns_hash
    render json: comment_list.to_json
  end

  def search_pending_campaign
    @pending_campaigns = Campaign.search_pending_campaign(params[:keyword])
  end

  def get_calls_stat
    calls_stat_list = Campaign.get_calls_stat_hash(params[:campaign_id], params[:status])
    render json: calls_stat_list.to_json
  end

  def get_calls_forever
    campaign_stat = Campaign.find(params[:id]).campaign_stat rescue nil
    render :text => campaign_stat.try(:total_calls_made_count_life) || 0
  end

  def get_calls_today
    campaign_stat = Campaign.find(params[:id]).campaign_stat rescue nil
    render :text => campaign_stat.try(:total_calls_made_count_today) || 0
  end

  def get_donation_amount
    campaign_stat = Campaign.find(params[:id]).campaign_stat rescue nil
    render :text => campaign_stat.try(:amount_donations_life).to_i || 0
  end

  def get_calls_in_progress
    campaign_stat = Campaign.find(params[:id]).campaign_stat rescue nil
    render :text => campaign_stat.try(:calls_in_progress) || 0
  end
  
  def get_population_destribution_pyramid_chart
    @campaign = Campaign.find(params[:id])
    respond_to do |format|
      format.html
      format.xml
    end 
  end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
  def total_destribution
    donation = @campaign.campaign_stat.amount_donations_life || 0
    answered = @campaign.stats_custom_by_code("PU","calls_life")
    no_answer = @campaign.campaign_stat.no_answer_calls_count_life || 0
    interested = @campaign.get_interested_calls("calls_life")
    left_msg_life = @campaign.stats_custom_by_code("AL","calls_life") + @campaign.stats_custom_by_code("AA","calls_life")
    transferred = @campaign.campaign_stat.transferred_count_life || 0
    opted_out = @campaign.stats_custom_by_code("NI","calls_life")
    recorded = @campaign.campaign_stat.recordings_count_life || 0
    
   return  answered + no_answer + interested + left_msg_life + transferred + opted_out + recorded
  end
  

  def answered_life(campaign)
    (campaign.stats_custom_by_code("PU","calls_life") / total_destribution.to_f) * 100 rescue 0
  end
  
  def no_answer_life(campaign)
    (campaign.campaign_stat.no_answer_calls_count_life  / total_destribution.to_f) * 100 rescue 0
  end

  def interested_life(campaign)
    (campaign.get_interested_calls("calls_life") / total_destribution.to_f) * 100 rescue 0
  end

  def left_msg_life_life(campaign)
    ((campaign.stats_custom_by_code("AL","calls_life") + campaign.stats_custom_by_code("AA","calls_life")) / total_destribution.to_f) * 100 rescue 0
  end

  def transferred_life(campaign)
    (campaign.campaign_stat.transferred_count_life / total_destribution.to_f) * 100 rescue 0
  end

  def opted_out_life(campaign)
    (campaign.stats_custom_by_code("NI","calls_life") / total_destribution.to_f) * 100 rescue 0
  end

  def recorded_life(campaign)
    (campaign.campaign_stat.recordings_count_life / total_destribution.to_f) * 100 rescue 0
  end
  
end

app/views/campaigns/_campaign_detail_overview_chats.html.erb
<!-- BEGIN PORTLET-->
<div class="portlet">
  <div class="portlet-title line">
    <div class="caption"><i class="icon-comments"></i>Chats <b class="badge badge-important">299</b></strong></a></li></div>
      <div class="tools">
        <a href="javascript:;" class="collapse"></a>
        <a href="#portlet-config" data-toggle="modal" class="config"></a>
        <a href="javascript:;" class="reload"></a>
        <a href="javascript:;" class="remove"></a>
      </div>
    </div>
  <div class="portlet-body" id="chats">
    <div class="scroller" data-height="343px" data-always-visible="1" data-rail-visible1="1">
      <ul class="chats">
        <li class="in">
          <img class="avatar" alt="" src="/assets/avatar1.jpg" />
          <div class="message">
            <span class="arrow"></span>
            <a href="#" class="name">Bob Nilson</a>
            <span class="datetime">at Jul 25, 2012 11:09</span>
            <span class="body">
              Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.
            </span>
          </div>
        </li>
        <li class="out">
          <img class="avatar" alt="" src="/assets/avatar2.jpg" />
          <div class="message">
            <span class="arrow"></span>
            <a href="#" class="name">Lisa Wong</a>
            <span class="datetime">at Jul 25, 2012 11:09</span>
            <span class="body">
              Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.
            </span>
          </div>
        </li>
        <li class="in">
          <img class="avatar" alt="" src="/assets/avatar1.jpg" />
          <div class="message">
            <span class="arrow"></span>
            <a href="#" class="name">Bob Nilson</a>
            <span class="datetime">at Jul 25, 2012 11:09</span>
            <span class="body">
              Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.
            </span>
          </div>
        </li>
        <li class="out">
          <img class="avatar" alt="" src="/assets/avatar3.jpg" />
          <div class="message">
            <span class="arrow"></span>
            <a href="#" class="name">Richard Doe</a>
            <span class="datetime">at Jul 25, 2012 11:09</span>
            <span class="body">
              Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.
            </span>
          </div>
        </li>
        <li class="in">
          <img class="avatar" alt="" src="/assets/avatar3.jpg" />
          <div class="message">
            <span class="arrow"></span>
            <a href="#" class="name">Richard Doe</a>
            <span class="datetime">at Jul 25, 2012 11:09</span>
            <span class="body">
              Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.
            </span>
          </div>
          </li>
          <li class="out">
            <img class="avatar" alt="" src="/assets/avatar1.jpg" />
            <div class="message">
              <span class="arrow"></span>
              <a href="#" class="name">Bob Nilson</a>
              <span class="datetime">at Jul 25, 2012 11:09</span>
              <span class="body">
                Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.
              </span>
            </div>
            </li>
            <li class="in">
              <img class="avatar" alt="" src="/assets/avatar3.jpg" />
              <div class="message">
                <span class="arrow"></span>
                <a href="#" class="name">Richard Doe</a>
                <span class="datetime">at Jul 25, 2012 11:09</span>
                <span class="body">
                  Lorem ipsum dolor sit amet, consectetuer adipiscing elit, 
                  sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.
                </span>
              </div>
           </li>
        </ul>
     </div>
     <div class="chat-form">
       <div class="input-cont">   
         <input class="m-wrap" type="text" placeholder="Type a message here..." />
       </div>
       <div class="btn-cont"> 
         <span class="arrow"></span>
         <a href="javascript:;" class="btn blue icn-only"><i class="icon-ok icon-white"></i></a>
       </div>
     </div>
  </div>
</div>
<!-- END PORTLET-->

app/views/campaigns/_campaign_detail_overview_info.html.erb
<!-- BEGIN SAMPLE TABLE PORTLET-->
<div class="portlet">
  <div class="portlet-body">
    <div class="portlet-body">
      <div class="row-fluid">
        <div class="span6 responsive popovers" data-tablet="span6" data-desktop="span6" data-trigger="hover" data-placement="left" data-content="Picked up and listened to all or a portion of the message but hung up the phone" data-original-title="Picked up, Hung up">
          <div class="circle-stat">
            <div class="visual">
              <input class="knobify" data-width="115" data-fgcolor="#4b8df8" data-thickness=".2" data-skin="tron" data-displayprevious="true" value="<%= @campaign.stats_custom_by_code("PU","calls_today") rescue 0 %>" data-max="<%= @campaign.stats_custom_by_code("PU","calls_life") rescue 0 %>" data-min="0" />
            </div>
            <div class="details">
              <div class="title">Answered <i class="icon-caret-up"></i></div>
                <div class="number">
                  <span class="sale-num" id="calls_answered_<%=@campaign.id%>"><%=@campaign.stats_custom_by_code("PU","calls_life") rescue 0 %> </span>
                </div>
              </div>
            </div>
          </div>
          <div class="span6 responsive popovers" data-tablet="span6 fix-margin" data-desktop="span6" data-trigger="hover" data-placement="left" data-content="When called the number exceeded the maximum ring time." data-original-title="No answer or bad number">
            <div class="circle-stat block">
              <div class="visual">
                <input class="knobify" data-width="115" data-fgcolor="#852b99" data-thickness=".2" data-skin="tron" data-displayprevious="true" value="<%= (@campaign.campaign_stat.no_answer_calls_count_today rescue 0) || 0 %>" data-max="<%= (@campaign.campaign_stat.no_answer_calls_count_life rescue 0) || 0 %>" data-min="0" />
              </div>
              <div class="details">
                <div class="title">No Answer <i class="icon-caret-up"></i></div>
                <div class="number"><span class="sale-num" id="no_answer_<%=@campaign.id%>"><%= (@campaign.campaign_stat.no_answer_calls_count_life rescue 0) || 0 %></span></div>                                 
              </div>
            </div>
          </div>
        </div>
        <div class="row-fluid">
          <div class="span6 responsive popovers" data-tablet="span6" data-desktop="span6" data-trigger="hover" data-placement="left" data-content="After they picked up the message was played, and the caller pressed 1 to connect with their elected official" data-original-title="Caller listened and selected option 1">
            <div class="circle-stat block">
              <div class="visual">
                <input class="knobify" data-width="115" data-fgcolor="#ffb848" data-thickness=".2" data-skin="tron" data-displayprevious="true" value="<%= @campaign.get_interested_calls("calls_today") || 0 %>" data-max="<%= @campaign.get_interested_calls("calls_life") || 0 %>" data-min="0" />
              </div>
              <div class="details">
                <div class="title">Interested <i class="icon-caret-down down"></i></div>
                <div class="number"><span class="sale-num" id="calls_interested_<%=@campaign.id%>">
                <%= (@campaign.get_interested_calls("calls_life")) || 0 %>
              </div>
            </div>
          </div>
        </div>
        <div class="span6 responsive popovers" data-tablet="span6 fix-margin" data-desktop="span6" data-trigger="hover" data-placement="left" data-content="The system automatically leaves a custom message for answering machines when they are detected." data-original-title="Left message on answering machine">
          <div class="circle-stat block">
          <%
           left_msg_today = @campaign.stats_custom_by_code("AL","calls_today") + @campaign.stats_custom_by_code("AA","calls_today")
           left_msg_life = @campaign.stats_custom_by_code("AL","calls_life") + @campaign.stats_custom_by_code("AA","calls_life")
          %>
            <div class="visual">
              <input class="knobify" data-width="115" data-fgcolor="#e02222" data-thickness=".2" data-skin="tron" data-displayprevious="true" value="<%= left_msg_today %> " data-max="<%= left_msg_life %>" data-min="0" />
            </div>
            <div class="details">
              <div class="title">Left Message <i class="icon-caret-up"></i></div>
                <div class="number"><span class="sale-num" id="left_message_<%=@campaign.id%>">
                  <%= left_msg_life %></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!--new one-->
      <div class="row-fluid">
        <div class="span6 responsive popovers" data-tablet="span6" data-desktop="span6" data-trigger="hover" data-placement="left" data-content="The caller successfully called their elected official" data-original-title="Successfully Connected">
          <div class="circle-stat">
            <div class="visual">
              <input class="knobify" data-width="115" data-fgcolor="#4b8df8" data-thickness=".2" data-skin="tron" data-displayprevious="true" value="<%= (@campaign.campaign_stat.transferred_count_today rescue 0) || 0 %>" data-max="<%= (@campaign.campaign_stat.transferred_count_life rescue 0) || 0 %>" data-min="0" />
            </div>
            <div class="details">
              <div class="title">Transferred <i class="icon-caret-up"></i></div>
              <div class="number"><span class="sale-num" id="calls_transferred_<Transf%=@campaign.id%>"><%= (@campaign.campaign_stat.transferred_count_life rescue 0) || 0 %><!--transferred_count_.campaign_stats--></span>
            </div>
          </div>
        </div>
      </div>
      <div class="span6 responsive popovers" data-tablet="span6 fix-margin" data-desktop="span6" data-trigger="hover" data-placement="left" data-content="The caller actively wished to be removed from future calls." data-original-title="Pressed 9 to Opt out">
        <div class="circle-stat block">
          <div class="visual">
            <input class="knobify" data-width="115" data-fgcolor="#852b99" data-thickness=".2" data-skin="tron" data-displayprevious="true" value="<%= @campaign.stats_custom_by_code("NI","calls_today") %>" data-max="<%= @campaign.stats_custom_by_code("NI","calls_life") %>" data-min="0" />
          </div>
          <div class="details">
            <div class="title">Opted Out <i class="icon-caret-up"></i></div>
              <div class="number"><%= @campaign.stats_custom_by_code("NI","calls_life") %></div>
            </div>
          </div>
        </div></div>
        <div class="row-fluid">
        <div class="span6 responsive popovers" data-tablet="span6" data-desktop="span6" data-trigger="hover" data-placement="left" data-content="The caller elected to publish their call to the website and it was approved by our moderators" data-original-title="Call recording published">
          <div class="circle-stat block">
            <div class="visual">
              <input class="knobify" data-width="115" data-fgcolor="#ffb848" data-thickness=".2" data-skin="tron" data-displayprevious="true" value="<%= (@campaign.campaign_stat.recordings_count_today rescue 0) || 0 %>" data-max="<%= (@campaign.campaign_stat.recordings_count_life rescue 0) || 0 %>" data-min="0" />
            </div>
            <div class="details">
              <div class="title">Recorded <i class="icon-caret-down down"></i></div>
                <div class="number"><span class="sale-num" id="calls_recorded_<%=@campaign.id%>"><%= (@campaign.campaign_stat.recordings_count_life rescue 0) || 0 %></span>
              </div>    
            </div>
          </div>
        </div>
        <div class="span6 responsive popovers" data-tablet="span6 fix-margin" data-desktop="span6" data-trigger="hover" data-placement="left" data-content="The caller pressed 6 to share the campaign with friends and family." data-original-title="Referred a friend">
          <div class="circle-stat block">
            <div class="visual">
              <input class="knobify" data-width="115" data-fgcolor="#e02222" data-thickness=".2" data-skin="tron" data-displayprevious="true" value="0" data-max="100" data-min="0" />
            </div>
            <div class="details">
              <div class="title">Shared <i class="icon-caret-up"></i></div>
              <div class="number">0</div>
            </div>
          </div>
        </div>
      </div>
      <!-- END PORTLET-->
    </div>
    <!-- END SAMPLE TABLE PORTLET-->

app/views/campaigns/_form.html.erb
<%= nested_form_for(@campaign, {:multipart => true}) do |f| %>
  <% if @campaign.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@campaign.errors.count, "error") %> prohibited this vendor from being saved:</h2>

      <ul>
      <% @campaign.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "campaign_name" %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "Category" %><br />
    <%= f.collection_select :category_id, Category.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label "Campaign Type" %><br />
    <%= f.collection_select :campaign_type_id, CampaignType.all, :id , :name %>
  </div>
  <div class="field">
    <%= f.label "Description" %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label "Short Description" %><br />
    <%= f.text_field :shortdescription %>
  </div>
  <div class="field">
    <%= f.label "Vici Campaign Id" %><br />
    <%= f.text_field :vici_campaign_id %>
  </div>
  <div class="field">
    <%= f.label "Transcript Text" %><br />
    <%= f.text_area :transcript_text %>
  </div>
  <div class="field">
    <%= f.label "Transcript Audio File" %><br />
    <%= f.text_field :transcript_audio_file %>
  </div>
  <div class="field">
    <%= f.label "Campaign Start Date" %><br />
    <%= f.date_select :campaign_start_date_time %>
  </div>
  <div class="field">
    <%= f.label "Campaign_end_date" %><br />
    <%= f.date_select :campaign_end_date_time %>
  </div>
  <div class="field">
    <%= f.label "Upload Image" %><br />
    <%= f.fields_for :campaign_images, :multiple => true do |x| %>
      <%= x.file_field :campimage %><br />
      <%= f.label "Image Name" %><br />
      <%= x.text_field :image_name %>
      <%= x.link_to_remove "Remove Image"%>
    <% end %>
    <p><%= f.link_to_add "Add an Image", :campaign_images %></p>
  </div>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/campaigns/_show_campaign.html.erb
  <h6>Name : <%= link_to @campaign.name, campaign_path(@campaign) rescue "" %></h6>
  <h6><%= @campaign.campaign_start_date_time rescue "" %></h6>
  <h6><%= @campaign.campaign_end_date_time rescue "" %></h6>
  <h6><%= @campaign.shortdescription rescue "" %></h6>
  <% if @campaign.campaign_images %>
    <h6> Campaign Images: </h6>
    <% @campaign.campaign_images.each do |img| %>
      <%= image_tag img.campimage_url(:thumb) %><br />
    <% end %>
  <% end %>
  <% if @campaign.campaign_stat %>
    <h6> Campaign Stats: </h6>
    <% @campaign.campaign_stat do |stat| %>
      <h6> Dialable Leads : <%= stat.dialable_leads rescue ""%></h6>
      <h6> Dialable Leads : <%= stat.calls_in_progress rescue ""%></h6>
    <% end %>
  <% end %>

app/views/campaigns/edit.html.erb
<h4>Suggest A Campaign</h4>

<%= render 'form' %>

<%= link_to 'Back', campaigns_path %>

app/views/campaigns/get_population_destribution_pyramid_chart.xml.erb
<?xml version="1.0" encoding="utf-8"?>
<chart manageResize="1" dataStreamURL='<%= get_population_destribution_pyramid_chart_campaign_path(@campaign.id) %>' refreshInterval='6' bgColor="CCCCCC,FFFFFF"  caption="Population Distribution" baseFontColor="333333" decmials="0" numberSuffix="%" pyramidYScale="40" captionPadding="0" isSliced="1">
        <set value="<%= answered_life(@campaign) %>" label="Answered" color="0066CC"/>
        <set value="<%= no_answer_life(@campaign) %>" label="No Answered" color="852b99"/>
        <set value="<%= interested_life(@campaign) %>" label="Interested" color="FFCC33" />
        <set value="<%= left_msg_life_life(@campaign) %>" label="Left Message" color="A10303"/>
        <set value="<%= transferred_life(@campaign) %>" label="Transferred" color="0066CC"/>
        <set value="<%= opted_out_life(@campaign) %>" label="Opted Out" color="852b99"/>
        <set value="<%= recorded_life(@campaign) %>" label="Recorded" color="FFCC33 "/>
        <set value="10" label="Shared" color="A10303"/>
      </chart>

app/views/campaigns/new.html.erb
<h4>Suggest A Campaign</h4>

<%= render 'form' %>

<%= link_to 'Back', campaigns_path %>

app/views/campaigns/show.js.erb
$("#show_camp").html("<%= escape_javascript(render(:partial => 'show_campaign')) %>");