config/routes.rb
Cfa::Application.routes.draw do
  
  

  root :to => "home#index"
  
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources :users
  resources :campaigns do
    collection do
      get 'get_campaigns_data'
      get 'search_pending_campaign'
      get 'get_calls_stat'
    end
    member do
      get 'get_calls_forever'
      get 'get_calls_today'
      get 'get_donation_amount'
      get 'get_calls_in_progress'
      get 'get_population_destribution_pyramid_chart', :format => :xml
    end
  end

  resources :campaign_globals do
    collection do
      get 'get_total_calls_forever'
      get 'get_total_calls_today'
      get 'get_donation_remaining'
      get 'get_calls_in_progress'
    end
  end

  resources :donations do
    collection do
      get 'has_donated'
    end
  end

  match 'donations/express_checkout' => "donations#express_checkout", :as => :donations_express_checkout, :via => :post
  
  ActiveAdmin.routes(self)

end

app/views/layouts/_header.html.erb
<div class="header navbar navbar-inverse navbar-fixed-top">
  <!-- BEGIN TOP NAVIGATION BAR -->
  <div class="navbar-inner">
	 <div class="container-fluid">
		<!-- BEGIN LOGO -->
		<a class="brand" href="/">
		<img src="/assets/logo.png" alt="logo" />
		</a>
		<!-- END LOGO -->
		<!-- BEGIN HORIZANTAL MENU -->
		<div class="navbar hor-menu hidden-phone hidden-tablet">
		   <div class="navbar-inner">
			  <ul class="nav">
				 <li class="visible-phone visible-tablet">
					<!-- BEGIN RESPONSIVE QUICK SEARCH FORM -->
					<form class="sidebar-search">
					   <div class="input-box">
						  <a href="javascript:;" class="remove"></a>
						  <input type="text" placeholder="Search..." />
						  <input type="button" class="submit" value=" " />
					   </div>
					</form>
					<!-- END RESPONSIVE QUICK SEARCH FORM -->
				 </li>
				 <li>
					<a href="index.html">
					Home
					</a>
				 </li>
				 <li  class="active">
					<a data-toggle="dropdown" class="dropdown-toggle" href="javascript:;">
					<span class="selected"></span>
					Campaigns
					<span class="arrow"></span>
					</a>
					<ul class="dropdown-menu">
								 <li class="dropdown-submenu">
						  <a href="javascript:;">
						  by Subject
						  <span class="arrow"></span>
						  </a>
						  <ul class="dropdown-menu">
							
							 <li class="dropdown-submenu">
								<a href="javascript:;">Health<span class="arrow"></span></a>
								<ul class="dropdown-menu">
								   <li><a href="index.html">Safe Food</a></li>
								   <li><a href="index.html">Clean Water</a></li>
								   <li><a href="index.html">Medical Care</a></li>
								   <li><a href="index.html">Alternative Treatments</a></li>
								</ul>
							 </li>
               <li class="dropdown-submenu">
                 <a href="javascript:;">Government<span class="arrow"></span></a>
								 <ul class="dropdown-menu">
                   <li class="dropdown-submenu">
								     <a href="javascript:;">Congress<span class="arrow"></span></a>
								     <ul class="dropdown-menu">
								       <li><a href="index.html">Free Speech</a></li>
                       <li><a href="index.html">Gun Rights</a></li>
								       <li><a href="index.html">4th Amendment</a></li>
                       <li><a href="index.html">Immigration</a></li>
                     </ul>
							     </li>
                   <li class="dropdown-submenu">
                     <a href="javascript:;">Executive Branch<span class="arrow"></span></a>
                     <ul class="dropdown-menu">
                       <li><a href="index.html">Executive Orders</a></li>
                       <li><a href="index.html">Pardons</a></li>
                       <li><a href="index.html">Treaties</a></li>
                       <li><a href="index.html">Justice Department</a></li>
                     </ul>
                   </li>
                 </ul>
							 </li>
							 <li class="dropdown-submenu">
								 <a href="javascript:;">Environmental<span class="arrow"></span></a>
								 <ul class="dropdown-menu">
                   <li><a href="index.html">Global Warming</a></li>
								   <li><a href="index.html">Fracking</a></li>
                   <li><a href="index.html">Geo Engineering</a></li>
                   <li><a href="index.html">Alternative Treatments</a></li>
                 </ul>
               </li> 
               <li class="dropdown-submenu">
                 <a href="javascript:;">Privacy<span class="arrow"></span></a>
								 <ul class="dropdown-menu">
								   <li><a href="index.html">Smart Meters</a></li>
								   <li><a href="index.html">Big Brother</a></li>
								 </ul>
							 </li> 
               <li class="dropdown-submenu">
                 <a href="javascript:;">Political Elections<span class="arrow"></span></a>
								 <ul class="dropdown-menu">
								   <li><a href="index.html">Federal</a></li>
								   <li><a href="index.html">State</a></li>
								   <li><a href="index.html">Local</a></li>                                       
								 </ul>
               </li>
							 <li><a href="index.html">Groups / Organizations</a></li>
							 <li><a href="index.html">Personal / Individual</a></li>
             </ul>
					   </li>
						 <li class="dropdown-submenu">
               <a href="javascript:;">
						     by Feature
						    <span class="arrow"></span>
						  </a>
						  <ul class="dropdown-menu">
              <li>
                <a href="javascript:;">Connect To Elected Official</a>
              </li>
              <li>
                <a href="javascript:;">Connect To Live Agent</a>
              </li>
							<li>
                <a href="javascript:;">Audio Comment Rant Line</a>
              </li>
              <li>
								<a href="javascript:;">Survey / Polls</a>
              </li>
              <li>
								<a href="javascript:;">Radio & TV Call-In Shows</a>
              </li>
              <li>
								<a href="javascript:;">Self-Help Information Menu</a>
              </li>
              <li>
								<a href="javascript:;">Private Group Messaging</a>
              </li>
              <li>
                <a href="javascript:;">Text to Speech Reader</a>
              </li>
            </ul>
          </li>
        </ul>
        <b class="caret-out"></b>
      </li>	
      <li>
        <a data-toggle="dropdown" class="dropdown-toggle" href="">Special Features
					<span class="arrow"></span>
        </a>
        <ul class="dropdown-menu">
          <li><a href="index.html">Alerts</a></li>
          <li><a href="index.html">Talk Show Call-In</a></li>
          <li><a href="index.html">Private Group Messaging</a></li>
          <li><a href="index.html">Text To Speech Reader</a></li>
        </ul>
				<b class="caret-out"></b>
      </li>				
      <li>
        <a href="">Donate</a>
      </li>
			<li>
			  <a href="">About</a>
      </li>
			<li>
			  <span class="hor-menu-search-form-toggler">&nbsp;</span>
				<div class="search-form hidden-phone hidden-tablet">
				  <form class="form-search">
					  <div class="input-append">
						  <input type="text" placeholder="Search..." class="m-wrap">
							  <button type="button" class="btn">Go</button>
            </div>
          </form>
        </div>
      </li>
    </ul>
  </div>
</div>
<!-- END HORIZANTAL MENU -->
<!-- BEGIN RESPONSIVE MENU TOGGLER -->
<a href="javascript:;" class="btn-navbar collapsed" data-toggle="collapse" data-target=".nav-collapse">
  <img src="/assets/menu-toggler.png" alt="" />
</a>
<!-- END RESPONSIVE MENU TOGGLER -->
<!-- BEGIN TOP NAVIGATION MENU -->
<ul class="nav pull-right">
  <!-- BEGIN USER LOGIN DROPDOWN -->
  <% unless current_user.blank? %>
    <li class="dropdown user">  
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <img alt="" src="/assets/avatar1_small.jpg" />
        <span class="username"><% if !current_user.blank? %><%= current_user.firstname rescue '' %>&nbsp;&nbsp;<%= current_user.lastname rescue '' %><% end %></span>
        <i class="icon-angle-down"></i>
      </a>
      <ul class="dropdown-menu">
        <li><a href="extra_profile.html"><i class="icon-user"></i> My Profile</a></li>
        <li><a href="calendar.html"><i class="icon-calendar"></i> My Calendar</a></li>
        <li><a href="inbox.html"><i class="icon-envelope"></i> My Inbox(3)</a></li>
        <li><a href="#"><i class="icon-tasks"></i> My Tasks</a></li>
        <li class="divider"></li>
        <li><i class="icon-key"></i>
          <% if user_signed_in? %>
            <li>
              <%= link_to('Sign Out', destroy_user_session_path, :method => :delete) %>        
            </li>
              <% else %>
            <li>
              <%= link_to('Sign In', new_user_session_path)  %>  
            </li>
          <% end %>      
        </li>
      </ul>
    </li>  
  <% else %>
    <li class="dropdown user">  
      <%= link_to 'Login', new_user_session_path %>
    </li>
    <li class="dropdown user">  
      <%= link_to 'Registration', new_user_registration_path %>
    </li>
  <% end %>    
  <!-- END USER LOGIN DROPDOWN -->
</ul
<!-- END TOP NAVIGATION MENU -->
</div>
</div>
<!-- END TOP NAVIGATION BAR -->
</div>
<!-- END HEADER -->

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">×</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Call For America", root_path, :class => 'brand' %>

<ul class="nav">
  <% if signed_in? %>
    <h4>Hi, <i><%= current_user.firstname rescue ""%></i></h4>
    <li>
    <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>        
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', new_user_session_path %>  
    </li>
    
  <% end %>
  <% if signed_in? %>
    <li>
    <%= link_to 'Edit account', edit_user_registration_path %>
    </li>
    <li>
    	<%= link_to 'Campaigns', campaigns_path %>
    </li>
    <li>
    <%= link_to 'Suggest A Campaign', new_campaign_path %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Call For America</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <script type="text/javascript">
      $(document).ready(function(){

        /*
        * Instance CirclePlayer inside jQuery doc ready
        *
        * CirclePlayer(jPlayerSelector, media, options)
        *   jPlayerSelector: String - The css selector of the jPlayer div.
        *   media: Object - The media object used in jPlayer("setMedia",media).
        *   options: Object - The jPlayer options.
        *
        * Multiple instances must set the cssSelectorAncestor in the jPlayer options. Defaults to "#cp_container_1" in CirclePlayer.
        */

        var myCirclePlayer = new CirclePlayer("#jquery_jplayer_1",
        {
          m4a: "http://www.jplayer.org/audio/m4a/Miaow-07-Bubble.m4a",
          oga: "http://www.jplayer.org/audio/ogg/Miaow-07-Bubble.ogg"
        }, {
          cssSelectorAncestor: "#cp_container_1"
        });

        // This code creates a 2nd instance. Delete if not required.

        var myOtherOne = new CirclePlayer("#jquery_jplayer_2",
        {
          m4a:"http://www.jplayer.org/audio/m4a/Miaow-04-Lismore.m4a",
          oga:"http://www.jplayer.org/audio/ogg/Miaow-04-Lismore.ogg"
        }, {
          cssSelectorAncestor: "#cp_container_2"
        });

        var myOthertwo = new CirclePlayer("#jquery_jplayer_3",
        {
          mp3:"http://labs.widewebsol.com/mit/CryOnMyShoulder.mp3"
        }, {
          supplied: "mp3",
          cssSelectorAncestor: "#cp_container_3"
        });
        var myOtherthree = new CirclePlayer("#jquery_jplayer_4",
        {
          mp3:"http://labs.widewebsol.com/mit/CryOnMyShoulder1.mp3"
        }, {
          supplied: "mp3",
          cssSelectorAncestor: "#cp_container_4"
        });
        var myOtherfour = new CirclePlayer("#jquery_jplayer_5",
        {
          mp3:"http://labs.widewebsol.com/mit/CryOnMyShoulder2.mp3"
        }, {
          supplied: "mp3",
          cssSelectorAncestor: "#cp_container_5"
        });
        var myOtherfive = new CirclePlayer("#jquery_jplayer_6",
        {
          mp3:"http://labs.widewebsol.com/mit/CryOnMyShoulder3.mp3"
        }, {
          supplied: "mp3",
          cssSelectorAncestor: "#cp_container_6"
        });
        var myOthersix = new CirclePlayer("#jquery_jplayer_7",
        {
          mp3:"http://labs.widewebsol.com/mit/CryOnMyShoulder4.mp3"
        }, {
          supplied: "mp3",
          cssSelectorAncestor: "#cp_container_7"
        });
      });
    </script>
  </head>
  <body class="fixed-top breakpoint-1280">
    <%= render 'layouts/header'%>	

    <%= yield %>

    <div class="footer">
      2013 &copy; Metronic by keenthemes.
      <div class="span pull-right">
        <span class="go-top"><i class="icon-angle-up"></i></span>
      </div>
    </div>
    <%= javascript_include_tag "bottom_section" %>
  </body>
</html>
<script>
  jQuery(document).ready(function() {
    App.init();
    Login.init();		
  });
</script>